### ISSUE TITLE
rolo 0.6 dispatching breaks with GenericAlias params

### ISSUE THREAD

**Issue by alexrashed** [localstack/rolo#19]
https://github.com/localstack/rolo/pull/14 added native support for Pydantic.
In order to detect Pydantic classes, the annotations / arguments of an endpoint function are traversed here:
https://github.com/localstack/rolo/blob/f3c553df646dedc43052e1a33f9c0bf75dc0875d/rolo/dispatcher.py#L86

Unfortunately, this breaks if you use any types which are not allowed to be used with `issubclass` like `GenericAlias` (something like `dict[str,str]`.
This breaks our dependency upgrade in LocalStack, as you can see in  our pipeline run here: https://app.circleci.com/pipelines/github/localstack/localstack/26921/workflows/2d5104c2-600f-43de-a6ad-775f091fe7a2/jobs/229933

Here's a simple reproducer (which doesn't really make sense, but shows the issue):
```
import pydantic  # noqa
from rolo import Request, Response, Router
from rolo.dispatcher import handler_dispatcher, ResultValue
from werkzeug.serving import run_simple


def foo(request: Request, matrix: dict[str, str] = None) -> ResultValue:
    return Response()


router = Router(dispatcher=handler_dispatcher())
router.add(
    "/",
    endpoint=foo,
)

# convert Router to a WSGI app and serve it through werkzeug
run_simple("localhost", 8080, router.wsgi(), use_reloader=True)
```

**Comment by bentsku** [comment]
I can add onto that. 

The CI failure was related to one router using incorrect typing for the `kwargs`  argument, using a dictionary instead of a value type. This was an issue which should be resolved with https://github.com/localstack/localstack/pull/11246

I thought that would be one of the only cases where we would use something "a bit wrong" which clashed with this conditional check. 

However, looking into how to type `kwargs`, we can now use `typing.Unpack` in combination with `TypedDict`. This also does not work with the conditional check above. 
This is the related data, related to PEP692: https://typing.readthedocs.io/en/latest/spec/callables.html#unpack-kwargs

Snippet:
```python
import pydantic  # noqa
from rolo import Request, Response, Router
from rolo.dispatcher import handler_dispatcher, ResultValue
from werkzeug.serving import run_simple


class Test(TypedDict, total=False):
    path: str
    random_value: str


def func(request: Request, **kwargs: Unpack[Test]) -> ResultValue:
    return Response()


router = Router(dispatcher=handler_dispatcher())
router.add(
    "/",
    endpoint=func,
    defaults={"path": "", "random_value": "dev"},
)

# convert Router to a WSGI app and serve it through werkzeug
run_simple("localhost", 8080, router.wsgi(), use_reloader=True)
```

**Comment by thrau** [comment]
thanks for the excellent reproducers @alexrashed and @bentsku! added both of them as tests and fixed the issue (or rather - explicitly ignored it for now)
